apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-server-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # This should match the size of your EBS volume
  storageClassName: gp2

